/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_io_github_kale_ko_srd_cpp_DesktopCapture
#define _Included_io_github_kale_ko_srd_cpp_DesktopCapture
#ifdef __cplusplus
extern "C" {
#endif
  /*
   * Class:     io_github_kale_ko_srd_cpp_DesktopCapture
   * Method:    connectDisplay
   * Signature: ()J
   */
  JNIEXPORT jlong JNICALL Java_io_github_kale_1ko_srd_cpp_DesktopCapture_connectDisplay(JNIEnv* env, jobject self);

  /*
   * Class:     io_github_kale_ko_srd_cpp_DesktopCapture
   * Method:    disconnectDisplay
   * Signature: (J)V
   */
  JNIEXPORT void JNICALL Java_io_github_kale_1ko_srd_cpp_DesktopCapture_disconnectDisplay(JNIEnv* env, jobject self, jlong displayHandle);

  /*
   * Class:     io_github_kale_ko_srd_cpp_DesktopCapture
   * Method:    getScreens
   * Signature: (J)[J
   */
  JNIEXPORT jlongArray JNICALL Java_io_github_kale_1ko_srd_cpp_DesktopCapture_getScreens(JNIEnv* env, jobject self, jlong displayHandle);

  /*
   * Class:     io_github_kale_ko_srd_cpp_DesktopCapture
   * Method:    captureScreen
   * Signature: (J)[B
   */
  JNIEXPORT jbyteArray JNICALL Java_io_github_kale_1ko_srd_cpp_DesktopCapture_captureScreen__J(JNIEnv* env, jobject self, jlong displayHandle);

  /*
   * Class:     io_github_kale_ko_srd_cpp_DesktopCapture
   * Method:    captureScreen
   * Signature: (JJ)[B
   */
  JNIEXPORT jbyteArray JNICALL Java_io_github_kale_1ko_srd_cpp_DesktopCapture_captureScreen__JJ(JNIEnv* env, jobject self, jlong displayHandle, jlong screenHandle);
#ifdef __cplusplus
}
#endif
#endif