y7nname: Build Test

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  makeLinux:
    name: "Make Natives - Linux"

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Dependencies
        run: |
          sudo apt-get install -y gcc-x86-64-linux-gnu g++-x86-64-linux-gnu gcc-i686-linux-gnu g++-i686-linux-gnu gcc-aarch64-linux-gnu g++-aarch64-linux-gnu gcc-arm-linux-gnueabi g++-arm-linux-gnueabi gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf
          sudo apt-get install -y apt install libx11-dev:amd64 libxrandr-dev:amd64 libx11-dev:i386 libxrandr-dev:i386 libx11-dev:arm64 libxrandr-dev:arm64 libx11-dev:armel libxrandr-dev:armel libx11-dev:armhf libxrandr-dev:armhf

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Compile Natives
        run: ./gradlew make

      - name: Upload Natives
        uses: actions/upload-artifact@v4
        with:
          name: "linux-natives"
          path: |
            build/natives/*.so
  makeWindows:
    name: "Make Natives - Windows"

    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Compile Natives
        run: ./gradlew make

      - name: Upload Natives
        uses: actions/upload-artifact@v4
        with:
          name: "windows-natives"
          path: |
            build/natives/*.dll
  build:
    name: "Build"
    needs: [ makeLinux, makeWindows ]

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Download Natives
        uses: actions/download-artifact@v4
        with:
          pattern: "*-natives"
          path: artifacts/
          merge-multiple: true

      - name: Extract Natives
        run: |
          ls artifacts/
          mkdir -p build/natives/
          cp artifacts/*/* build/natives/
          ls build/natives/

      - name: Build Artifacts
        run: ./gradlew build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "builds"
          path: |
            build/libs/SRD-*-client.jar
            build/libs/SRD-*-server.jar
            build/libs/SRD-*-manager.jar